version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  structured:
    format: '%(asctime)s | %(levelname)-8s | %(name)-20s | %(funcName)-15s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/tradingstation.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 5242880   # 5MB
    backupCount: 3

loggers:
  utils:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  jobs:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  screeners:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  orchestrator:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]