---
# S&P 500 Universe Configuration
universe_name: "sp500"
last_updated: "2024-01-01"
total_symbols: 503

# Symbol filtering criteria
filters:
  min_market_cap: 1000000000  # $1B minimum
  min_avg_volume: 500000      # 500k daily average
  exclude_sectors: []
  
# Manual ticker management
manual_tickers:
  search_paths:
    - "/workspace/tickerlist.txt"
    - "/workspace/data/tickerlist.txt"
    - "./tickerlist.txt"
  
  # Always include these tickers regardless of filters
  force_include:
    - "SPY"
    - "QQQ"
    - "IWM"

# Output configuration
output:
  master_list_path: "data/universe/master_tickerlist.txt"
  sp500_path: "data/universe/sp500.csv"
  backup_retention_days: 30

symbols:
  - symbol: "AAPL"
    name: "Apple Inc."
    sector: "Technology"
  - symbol: "MSFT"
    name: "Microsoft Corporation"
    sector: "Technology"
  - symbol: "GOOGL"
    name: "Alphabet Inc."
    sector: "Technology"
  - symbol: "AMZN"
    name: "Amazon.com Inc."
    sector: "Consumer Discretionary"
  - symbol: "TSLA"
    name: "Tesla Inc."
    sector: "Consumer Discretionary"
  # Note: This is a sample - full SP500 list would be much longer