name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']  # <-- no 3.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix['python-version'] }}
          cache: 'pip'
      - run: python -V
      - run: pip install -r requirements.txt || true
      - run: python -m compileall -q .
  
  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/dev' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sS -X POST "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json"