name: Fetch Once
on:
  workflow_dispatch:
    inputs:
      interval:
        description: '1min | 30min | daily'
        required: true
        default: '1min'
      tickers:
        description: 'Comma-separated e.g. AAPL,NVDA,TSLA,MSFT,AMZN'
        required: true
        default: 'AAPL,NVDA,TSLA,MSFT,AMZN'
      force_full:
        description: 'true/false'
        required: true
        default: 'true'
jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
      DEPLOYMENT_TAG: marketdata-trader-plan
      PROVIDER: marketdata
      MARKETDATA_ENDPOINT: ${{ vars.MARKETDATA_ENDPOINT }}
      MARKETDATA_TOKEN: ${{ secrets.MARKETDATA_TOKEN }}
      INTRADAY_EXTENDED: 'true'
      MARKET_TZ: America/New_York
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      SPACES_REGION: ${{ vars.SPACES_REGION }}
      SPACES_BUCKET_NAME: ${{ vars.SPACES_BUCKET_NAME }}
      SPACES_ENDPOINT: ${{ vars.SPACES_ENDPOINT }}
      SPACES_BASE_PREFIX: ${{ vars.SPACES_BASE_PREFIX }}
      DATA_ROOT: ${{ vars.DATA_ROOT }}
      UNIVERSE_KEY: ${{ vars.UNIVERSE_KEY }}
      LOG_LEVEL: INFO
      TZ: UTC
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || pip install boto3 pandas
      - name: Convert tickers
        run: echo "TICKERS=$(echo '${{ github.event.inputs.tickers }}' | tr ',' ' ')" >> $GITHUB_ENV
      - name: Run once
        run: |
          python -m jobs.data_fetch_manager \
            --job intraday \
            --interval ${{ github.event.inputs.interval }} \
            --tickers $TICKERS $([ "${{ github.event.inputs.force_full }}" = "true" ] && echo --force-full)