name: Inspect Spaces
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Prefix e.g. trading-system/data/intraday/1min/'
        required: true
        default: ''
      folders_only:
        description: 'true to list folders only'
        required: true
        default: 'false'
      num_lines:
        description: 'Show last N lines for CSV'
        required: true
        default: '3'
jobs:
  inspect:
    runs-on: ubuntu-latest
    env:
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      SPACES_REGION: ${{ vars.SPACES_REGION }}
      SPACES_ENDPOINT: ${{ vars.SPACES_ENDPOINT }}
      SPACES_BUCKET_NAME: ${{ vars.SPACES_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || pip install boto3 pandas
      - run: |
          python -m tools.inspect_spaces \
            --prefix "${{ github.event.inputs.prefix }}" \
            --folders-only "${{ github.event.inputs.folders_only }}" \
            --num-lines "${{ github.event.inputs.num_lines }}"