name: Redeploy DO App
on:
  workflow_dispatch: {}

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: |
          curl -sS -X POST "https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_ID }}/deployments" \
            -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}" \
            -H "Content-Type: application/json"