name: Repair S3 Paths
on:
  workflow_dispatch:
    inputs:
      apply:
        description: "true = apply, false = dry-run"
        required: true
        default: "false"
jobs:
  repair:
    runs-on: ubuntu-latest
    env:
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      SPACES_REGION: ${{ vars.SPACES_REGION }}
      SPACES_ENDPOINT: ${{ vars.SPACES_ENDPOINT }}
      SPACES_BUCKET_NAME: ${{ vars.SPACES_BUCKET_NAME }}
      SPACES_BASE_PREFIX: ${{ vars.SPACES_BASE_PREFIX }}   # trading-system
      DATA_ROOT: ${{ vars.DATA_ROOT }}                     # data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || pip install boto3 pandas
      - run: |
          if [ "${{ github.event.inputs.apply }}" = "true" ]; then
            python -m tools.repair_paths --apply
          else
            python -m tools.repair_paths --dry-run
          fi