[theme]
# Primary color for interactive elements and accents
primaryColor = "#007ACC"

# Main background color - dark charcoal for professional look
backgroundColor = "#1E1E1E"

# Secondary background color for sidebars and containers
secondaryBackgroundColor = "#252526"

# Text color - light for high contrast against dark background
textColor = "#FAFAFA"

# Font family
font = "sans serif"

[server]
# Disable file watcher for production deployment
fileWatcherType = "none"

# Allow CORS for deployment
enableCORS = false
enableXsrfProtection = false

[browser]
# Disable server statistics gathering for better privacy
gatherUsageStats = false